secret: thisisfordevelopmenttestsecret
log_level: debug
user:
  name: admin
  password: admin
store:
  type: postgres
  schema: chore
  host: "127.0.0.1"
  port: "5432"
  user: postgres
  dbName: postgres
