# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: chore

release:
  footer: |
    **Full Changelog**: https://github.com/worldline-go/chore/compare/{{ .PreviousTag }}...{{ .Tag }}

before:
  hooks:
    # build web
    - '{{ if index .Env "NOT_BUILD_FRONTEND" }}echo skipping build frontend{{else}}sh -c "./build.sh --build-front --copy"{{ end }}'
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/chore
    ldflags:
      - -s -w -X {{.ModulePath}}/internal/config.AppVersion={{.Version}} -X {{.ModulePath}}/internal/config.Env=PRODUCTION
    flags:
      - -trimpath
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

dockers:
- image_templates:
  - 'ghcr.io/worldline-go/chore:{{ .Tag }}'
  dockerfile: ci/Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/worldline-go/chore/main/README.md"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Eray Ates\",\"email\":\"eates23@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=Apache-2.0"
  - "--label=org.opencontainers.image.description=Export socket to HTTP"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - 'ghcr.io/worldline-go/chore:{{ .Tag }}-alpine3.16.2'
  dockerfile: ci/alpine.Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/worldline-go/chore/main/README.md"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Eray Ates\",\"email\":\"eates23@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=Apache-2.0"
  - "--label=org.opencontainers.image.description=Export socket to HTTP"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  - "--build-arg=ALPINE=alpine:3.16.2"
