version: "3"
services:
  postgres:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    volumes:
      - ./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
      # - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

